apiVersion: v1
kind: Secret
metadata:
    name: airflow-dags-secrets
    namespace: {{ .Values.namespace }} 
stringData:
    environment: {{ .Values.environment }} 
    vault_url: {{ .Values.vault.url }} # "https://vault.staging.earnest.com"
    vault_port: "443" # "443"
    vault_key: {{ .Values.vault.key }} # "airflow"
    vault_token: {{ .Values.vault.token }} #"a446702d-d31c-4b72-9494-63a7759d2f98"
    secret_key: {{ .Values.secret_key }} #"THIS IS UNSAFE!"
    fernet_key: {{ .Values.fernet_key }} #"7T512UXSSmBOkpWimFHIVb8jK6lfmSAvx4mO6Arehnc="
