apiVersion: v1
kind: Secret # this can be created straight from Vault with a CDR 
metadata:
  name: airflow-http-git-secret 
  namespace: {{ .Values.namespace }} 
  labels:
    {{- include "earnest-airflow2.labels" . | nindent 4 }}
stringData:
  username: {{ .Values.github.username }} 
  password: {{ .Values.github.token }} 
