apiVersion: v1
kind: Secret # this can be created straight from Vault with a CDR 
metadata:
  name: log-aws-token
  namespace: {{ .Values.namespace }} 
  labels:
    {{- include "earnest-airflow2.labels" . | nindent 4 }}
stringData:  
  AWS_ACCESS_KEY_ID: {{ .Values.logs.AWS_ACCESS_KEY_ID }}     
  AWS_SECRET_ACCESS_KEY: {{ .Values.logs.AWS_SECRET_ACCESS_KEY }}

