apiVersion: v1
kind: Pod
metadata:
  annotations:
    checksum/secret-config-envs: c76bc9bf3d21dc961103809245cbb235e695a04c4925b397f27699d84a9794d8
    checksum/secret-local-settings: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    checksum/sync-users-script: 8caa173b1df799c745becc439ca19f2c8527a10a91b735fb5a6252ffcd740018
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  creationTimestamp: "2022-05-31T17:05:03Z"
  generateName: data-airflow-2-sync-users-54c49cb7f6-
  labels:
    app: airflow
    component: sync-users
    pod-template-hash: 54c49cb7f6
    release: data-airflow-2
  name: data-airflow-2-sync-users-54c49cb7f6-74lzj
  namespace: airflow-2
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: data-airflow-2-sync-users-54c49cb7f6
    uid: cd7b65ab-863e-4d88-9a61-2036e10eb504
  resourceVersion: "363839"
  uid: 6758f765-6872-4b21-95d0-6f38ec30cde5
spec:
  affinity: {}
  containers:
  - args:
    - python
    - -u
    - /mnt/scripts/sync_users.py
    command:
    - /usr/bin/dumb-init
    - --
    - /entrypoint
    env:
    - name: DATABASE_USER
      value: postgres
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgresql-password
          name: data-airflow-2-postgresql
    - name: CONNECTION_CHECK_MAX_COUNT
      value: "0"
    envFrom:
    - secretRef:
        name: data-airflow-2-config-envs
    image: earnest/airflow_2:2.2.5-f71bdc5-linux-amd64
    imagePullPolicy: IfNotPresent
    name: sync-airflow-users
    resources: {}
    securityContext:
      runAsGroup: 0
      runAsUser: 50000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/airflow/dags
      name: dags-data
    - mountPath: /opt/airflow/logs
      name: logs-data
    - mountPath: /mnt/scripts
      name: scripts
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-58ph7
      readOnly: true
  - env:
    - name: GIT_SYNC_ROOT
      value: /dags
    - name: GIT_SYNC_DEST
      value: repo
    - name: GIT_SYNC_REPO
      value: git@github.com:Ivanwizeline/dags
    - name: GIT_SYNC_BRANCH
      value: main
    - name: GIT_SYNC_REV
      value: HEAD
    - name: GIT_SYNC_DEPTH
      value: "1"
    - name: GIT_SYNC_WAIT
      value: "60"
    - name: GIT_SYNC_TIMEOUT
      value: "120"
    - name: GIT_SYNC_ADD_USER
      value: "true"
    - name: GIT_SYNC_MAX_SYNC_FAILURES
      value: "0"
    - name: GIT_SYNC_SSH
      value: "true"
    - name: GIT_SSH_KEY_FILE
      value: /etc/git-secret/id_rsa
    - name: GIT_KNOWN_HOSTS
      value: "true"
    - name: GIT_SSH_KNOWN_HOSTS_FILE
      value: /etc/git-secret/known_hosts
    - name: DATABASE_USER
      value: postgres
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgresql-password
          name: data-airflow-2-postgresql
    - name: CONNECTION_CHECK_MAX_COUNT
      value: "0"
    envFrom:
    - secretRef:
        name: data-airflow-2-config-envs
    image: k8s.gcr.io/git-sync/git-sync:v3.5.0
    imagePullPolicy: IfNotPresent
    name: dags-git-sync
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
    securityContext:
      runAsGroup: 65533
      runAsUser: 65533
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /dags
      name: dags-data
    - mountPath: /etc/git-secret/id_rsa
      name: git-secret
      readOnly: true
      subPath: id_ed25519
    - mountPath: /etc/git-secret/known_hosts
      name: git-known-hosts
      readOnly: true
      subPath: known_hosts
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-58ph7
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - env:
    - name: GIT_SYNC_ONE_TIME
      value: "true"
    - name: GIT_SYNC_ROOT
      value: /dags
    - name: GIT_SYNC_DEST
      value: repo
    - name: GIT_SYNC_REPO
      value: git@github.com:Ivanwizeline/dags
    - name: GIT_SYNC_BRANCH
      value: main
    - name: GIT_SYNC_REV
      value: HEAD
    - name: GIT_SYNC_DEPTH
      value: "1"
    - name: GIT_SYNC_WAIT
      value: "60"
    - name: GIT_SYNC_TIMEOUT
      value: "120"
    - name: GIT_SYNC_ADD_USER
      value: "true"
    - name: GIT_SYNC_MAX_SYNC_FAILURES
      value: "0"
    - name: GIT_SYNC_SSH
      value: "true"
    - name: GIT_SSH_KEY_FILE
      value: /etc/git-secret/id_rsa
    - name: GIT_KNOWN_HOSTS
      value: "true"
    - name: GIT_SSH_KNOWN_HOSTS_FILE
      value: /etc/git-secret/known_hosts
    - name: DATABASE_USER
      value: postgres
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgresql-password
          name: data-airflow-2-postgresql
    - name: CONNECTION_CHECK_MAX_COUNT
      value: "0"
    envFrom:
    - secretRef:
        name: data-airflow-2-config-envs
    image: k8s.gcr.io/git-sync/git-sync:v3.5.0
    imagePullPolicy: IfNotPresent
    name: dags-git-clone
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
    securityContext:
      runAsGroup: 65533
      runAsUser: 65533
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /dags
      name: dags-data
    - mountPath: /etc/git-secret/id_rsa
      name: git-secret
      readOnly: true
      subPath: id_ed25519
    - mountPath: /etc/git-secret/known_hosts
      name: git-known-hosts
      readOnly: true
      subPath: known_hosts
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-58ph7
      readOnly: true
  - args:
    - bash
    - -c
    - exec timeout 60s airflow db check
    command:
    - /usr/bin/dumb-init
    - --
    - /entrypoint
    env:
    - name: DATABASE_USER
      value: postgres
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgresql-password
          name: data-airflow-2-postgresql
    - name: CONNECTION_CHECK_MAX_COUNT
      value: "0"
    envFrom:
    - secretRef:
        name: data-airflow-2-config-envs
    image: earnest/airflow_2:2.2.5-f71bdc5-linux-amd64
    imagePullPolicy: IfNotPresent
    name: check-db
    resources: {}
    securityContext:
      runAsGroup: 0
      runAsUser: 50000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/airflow/dags
      name: dags-data
    - mountPath: /opt/airflow/logs
      name: logs-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-58ph7
      readOnly: true
  - args:
    - bash
    - -c
    - exec airflow db check-migrations -t 60
    command:
    - /usr/bin/dumb-init
    - --
    - /entrypoint
    env:
    - name: DATABASE_USER
      value: postgres
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgresql-password
          name: data-airflow-2-postgresql
    - name: CONNECTION_CHECK_MAX_COUNT
      value: "0"
    envFrom:
    - secretRef:
        name: data-airflow-2-config-envs
    image: earnest/airflow_2:2.2.5-f71bdc5-linux-amd64
    imagePullPolicy: IfNotPresent
    name: wait-for-db-migrations
    resources: {}
    securityContext:
      runAsGroup: 0
      runAsUser: 50000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/airflow/dags
      name: dags-data
    - mountPath: /opt/airflow/logs
      name: logs-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-58ph7
      readOnly: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 0
  serviceAccount: data-airflow-2
  serviceAccountName: data-airflow-2
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: dags-data
  - emptyDir: {}
    name: logs-data
  - name: git-secret
    secret:
      defaultMode: 420
      secretName: airflow-ssh-git-secret
  - name: git-known-hosts
    secret:
      defaultMode: 420
      secretName: data-airflow-2-known-hosts
  - name: scripts
    secret:
      defaultMode: 420
      secretName: data-airflow-2-sync-users
  - name: kube-api-access-58ph7
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-05-31T17:05:03Z"
    message: 'containers with incomplete status: [dags-git-clone check-db wait-for-db-migrations]'
    reason: ContainersNotInitialized
    status: "False"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-05-31T17:05:03Z"
    message: 'containers with unready status: [sync-airflow-users dags-git-sync]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-05-31T17:05:03Z"
    message: 'containers with unready status: [sync-airflow-users dags-git-sync]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-05-31T17:05:03Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: k8s.gcr.io/git-sync/git-sync:v3.5.0
    imageID: ""
    lastState: {}
    name: dags-git-sync
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: PodInitializing
  - image: earnest/airflow_2:2.2.5-f71bdc5-linux-amd64
    imageID: ""
    lastState: {}
    name: sync-airflow-users
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: PodInitializing
  hostIP: 192.168.65.4
  initContainerStatuses:
  - image: k8s.gcr.io/git-sync/git-sync:v3.5.0
    imageID: ""
    lastState: {}
    name: dags-git-clone
    ready: false
    restartCount: 0
    state:
      waiting:
        reason: PodInitializing
  - image: earnest/airflow_2:2.2.5-f71bdc5-linux-amd64
    imageID: ""
    lastState: {}
    name: check-db
    ready: false
    restartCount: 0
    state:
      waiting:
        reason: PodInitializing
  - image: earnest/airflow_2:2.2.5-f71bdc5-linux-amd64
    imageID: ""
    lastState: {}
    name: wait-for-db-migrations
    ready: false
    restartCount: 0
    state:
      waiting:
        reason: PodInitializing
  phase: Pending
  qosClass: Burstable
  startTime: "2022-05-31T17:05:03Z"
