apiVersion: v1
kind: Pod
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  creationTimestamp: "2022-05-26T20:28:18Z"
  generateName: data-airflow-2-postgresql-
  labels:
    app: postgresql
    chart: postgresql-8.6.4
    controller-revision-hash: data-airflow-2-postgresql-657c8c4f98
    heritage: Helm
    release: data-airflow-2
    role: master
    statefulset.kubernetes.io/pod-name: data-airflow-2-postgresql-0
  name: data-airflow-2-postgresql-0
  namespace: airflow-2
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: data-airflow-2-postgresql
    uid: fe4cb9fa-13ee-4c3a-b0c4-ef91f87c2300
  resourceVersion: "307871"
  uid: 74c2dfcd-3169-4f3e-a15e-6b124a004401
spec:
  containers:
  - env:
    - name: BITNAMI_DEBUG
      value: "false"
    - name: POSTGRESQL_PORT_NUMBER
      value: "5432"
    - name: POSTGRESQL_VOLUME_DIR
      value: /bitnami/postgresql
    - name: PGDATA
      value: /bitnami/postgresql/data
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgresql-password
          name: data-airflow-2-postgresql
    - name: POSTGRES_DB
      value: airflow
    - name: POSTGRESQL_ENABLE_LDAP
      value: "no"
    image: docker.io/bitnami/postgresql:11.7.0-debian-10-r9
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - exec pg_isready -U "postgres" -d "airflow" -h 127.0.0.1 -p 5432
      failureThreshold: 6
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: data-airflow-2-postgresql
    ports:
    - containerPort: 5432
      name: tcp-postgresql
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - -e
        - |
          exec pg_isready -U "postgres" -d "airflow" -h 127.0.0.1 -p 5432
          [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
      failureThreshold: 6
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
    securityContext:
      runAsUser: 1001
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /dev/shm
      name: dshm
    - mountPath: /bitnami/postgresql
      name: data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-lb887
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: data-airflow-2-postgresql-0
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1001
  serviceAccount: default
  serviceAccountName: default
  subdomain: data-airflow-2-postgresql-headless
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-data-airflow-2-postgresql-0
  - emptyDir:
      medium: Memory
      sizeLimit: 1Gi
    name: dshm
  - name: kube-api-access-lb887
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-05-26T20:28:19Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-05-26T20:28:29Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-05-26T20:28:29Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-05-26T20:28:19Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://daeef009aa0d1b9c3c51af2fceb3404b37f58bfc2dfce5747232d951a47a5c1d
    image: bitnami/postgresql:11.7.0-debian-10-r9
    imageID: docker-pullable://bitnami/postgresql@sha256:f18ba80a1de4c8b93ff4bffa38f783c1e267c1e4a649e2b1296352a53fd12f1f
    lastState: {}
    name: data-airflow-2-postgresql
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-05-26T20:28:22Z"
  hostIP: 192.168.65.4
  phase: Running
  podIP: 10.1.0.174
  podIPs:
  - ip: 10.1.0.174
  qosClass: Burstable
  startTime: "2022-05-26T20:28:19Z"
