apiVersion: v1
kind: PersistentVolume
metadata:
  name: dags-pvc
  namespace: airflow-2
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: ${DAGS_PATH}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dags-pvc
  namespace: airflow-2
spec:
  storageClassName: hostpath
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: dags-pvc
